version: '3.3'

services:
  my-scheme:
    image: my-scheme
    volumes:
     - ./code/:/code/
    restart: always
    container_name: my-scheme
    command: /root/sh/entrypoint.sh
    ports:
      - '3333:3306'
    expose:
      - '3333'